#
# This config.toml is an example and based on the ananke theme
# https://github.com/theNewDynamic/gohugo-theme-ananke/.
#
# If you use a different theme, you might need to change the content of config.toml
# to your liking.
#

#
# Theme setup
#
# If you use go mod to install your theme, you must use the URL of the theme.
# If your theme is in the themes directory, you just need to specify its name.
#
#theme = "ananke"
#theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
theme = "DoIt"

baseURL = "https://tips.git4ta.fun"
title = "觅钥贴士"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
languageCode = "zh-CN"
resourceDir = "../resources"

DefaultContentLanguage = "zh-cn"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.zh-cn]
    weight = 1
    title = "觅钥贴士"
    languageCode = "zh-CN"
    languageName = "简体中文"

[menu]
  [[menu.main]]
    identifier = "技术"
    name = "技术"
    url = "/技术/"
    weight = 1
    
  [[menu.main]]
    identifier = "生活"
    name = "生活"
    url = "/生活/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 50

[params]
  version = "0.3.X"
  defaultTheme = "auto"
  gitRepo = ""
  fingerprint = ""
  dateFormat = "2006-01-02"
  description = "Welcome to my website"
  images = ["/logo.png"]

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      name = "觅钥贴士"
      typeit = false
    [params.header.menu]
      paginate = 10

  [params.footer]
    enable = true
    hugo = true
    copyright = true
    author = true
    since = 2023

  [params.home]
    rss = 10
    [params.home.profile]
      enable = false

  [params.social]
    GitHub = ""
    Twitter = ""
    Email = ""

  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = false
    ruby = true
    fraction = true

  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = "Search"
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false

  [params.list]
    paginate = 10
    dateFormat = "01-02"
    rss = 10

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params.author]
  name = "Ben"
  email = ""
  link = "https://tips.git4ta.fun"
  avatar = ""
