deploy:
  image: node:latest
  before_script:
    - chmod +x build.sh
    - npm install -g wrangler
    - wrangler login
  script:
    - ./build.sh
  retry:
    max: 2
    when:
      - runner_system_failure
      - api_failure
      - stuck_or_timeout_failure
  variables:
    GIT_STRATEGY: clone
    CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}