deploy:
  image: node:latest
  before_script:
    - chmod +x build.sh
    - npm install -g wrangler
  script:
    - ./build.sh
  retry:
    max: 2
    when:
      - runner_system_failure
      - api_failure
      - stuck_or_timeout_failure
  variables:
    GIT_STRATEGY: clone 